version: "3.9"

services:
  db:
    image: postgres:16
    container_name: telecom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: telecom
      POSTGRES_PASSWORD: telecom
      POSTGRES_DB: telecom_assistente
    ports:
      - "5434:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
